### ISSUE TITLE
but what is about categorical data generation ?

### ISSUE THREAD

**Issue by Sandy4321** [javism/synthetic_datasets_nspheres#1]
great code thanks
but what is about categorical data generation ?

**Comment by javism** [comment]
Hi!

Generating categorical data is not the purpose of this code. Also, these type of data cannot be easily incorporated into the concept of n-spheres as a way of controlling properties of the dataset in a n-dimensional space. 

If you want to work with categorical data, there are other alternatives here: 
https://www.kdnuggets.com/2019/09/scikit-learn-synthetic-dataset.html

best

**Comment by Sandy4321** [comment]
it is the point
scikit-learn is not generating categorical data

**Comment by javism** [comment]
I close this issue since it is not related to the software.
